Get /api
omar-baggio/NcNews-SoloProject pull request #3
Opened 2023-06-26 15:31 UTC by omar-baggio

2023-06-26 15:46 UTC, Jodiech requested changes
Hey 👋 great work on this ticket! There are just a few tweaks to be made to your tests, then you're good to go! Please submit another PR once you have made these changes 👍

2023-06-26 15:46 UTC, Jodiech commented on __tests__/app.test.js
> +      });
You should be more specific about what form this JSON file should take. Maybe have a look at .toMatchObject( ) and expect.objectContaining( ) 👀

2023-06-26 15:46 UTC, Jodiech commented on controller/api.controller.js
> +  res.status(200).send(endpoints);
I'd consider sending this back destructured 👀

2023-06-26 15:46 UTC, Jodiech commented on __tests__/app.test.js
> +  test("404: responds with error message page not found", () => {
You can do a test for a 404, but it shouldn't be in the same describe block for this ticket as it's not specific to this endpoint. Please separate this out 👍

2023-06-27 09:05 UTC, lewispricey approved these changes
Great work on this ticket Omar, thanks for implementing the changes Jodie suggested.

For your api endpoint tests you could check that each of the endpoint keys ("GET /api" ect.) contains an object that has the 4 expected properties rarther than checking the endpoint keys themselves (mainly so you don't have to go back and update this test for every endpoint) but what you have gives us confidence that you are recieving the endpoint data back so this is absolutely fine. 💯 

Good to merge when you're ready 🚀

2023-06-27 09:05 UTC, lewispricey commented on __tests__/app.test.js
> +      .then(({ body: { endpoints } }) => {
Nice use of destructuring here to access the endpoints key

2023-06-27 10:01 UTC, merged